# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7969601d73cd85fc6da09a93afe166f838fefa9133183741369a4ee5f6811c51ad0de303808767c964fa9f219071f9429349e1ee2edc7fa51b7f4a88a864eadc

test:
  secret_key_base: 3b8017223617a70b1e0d84f98a4bfd8e316eb3b19072a801e301c4df57c7085a99e5a6b3f885408a15ad682249249ebec9683cdb0612876d62221a43dca17643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
